apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    app: gitea
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitea-hostpath
  hostPath:
    path: /run/desktop/mnt/host/c/Shailesh/Python/DevOps/data/gitea
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
  labels:
    app: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gitea-hostpath
  volumeName: gitea-pv
