apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-credentials-setup
  namespace: jenkins
data:
  credentials-setup.groovy: |
    import jenkins.model.*
    import hudson.model.*
    import java.io.*
    
    def instance = Jenkins.getInstance()
    
    // Wait for Jenkins to be fully initialized
    Thread.sleep(25000)
    
    println "Setting up Jenkins credentials..."
    
    try {
        // Create credentials directory structure
        def credentialsDir = new File(instance.getRootDir(), "credentials.xml")
        
        // Create a simple credentials configuration
        def credentialsXml = '''<?xml version='1.1' encoding='UTF-8'?>
    <com.cloudbees.plugins.credentials.SystemCredentialsProvider plugin="credentials@2.6.1">
      <domainCredentialsMap class="hudson.util.CopyOnWriteMap$Hash">
        <entry>
          <com.cloudbees.plugins.credentials.domains.Domain>
            <specifications/>
          </com.cloudbees.plugins.credentials.domains.Domain>
          <java.util.concurrent.CopyOnWriteArrayList>
            <com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
              <scope>GLOBAL</scope>
              <id>gitea-credentials</id>
              <description>Gitea credentials for Jenkins</description>
              <username>admin</username>
              <password>{AQAAABAAAAAQAAAAA}</password>
            </com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
          </java.util.concurrent.CopyOnWriteArrayList>
        </entry>
      </domainCredentialsMap>
    </com.cloudbees.plugins.credentials.SystemCredentialsProvider>'''
        
        // Write credentials.xml
        credentialsDir.text = credentialsXml
        
        println "Credentials setup complete!"
        
    } catch (Exception e) {
        println "Error during credentials setup: ${e.message}"
        e.printStackTrace()
    }
